project: 
  type: book
  output-dir: docs

book:
  title: "Quarto for Scientists"
  author: "Nicholas Tierney"
  description: | 
     For a scientific report to be completely credible, it must be reproducible. 
     The full computational environment used to derive the results, including 
     the data and code used for statistical analysis should be available for 
     others to reproduce. Quarto is a tool that allows you integrate your 
     code, text and figures in a single file in order to make high quality, 
     reproducible reports. A paper published with an included quarto file and 
     data sets can be reproduced by anyone with a computer.
  site-url: https://qmd4sci.njtierney.com
  repo-url: https://github.com/njtierney/qmd4sci
  repo-branch: main
  repo-actions: [edit, issue]
  # sharing: [twitter]
  date: "2025-04-09"
  page-footer: "Copyright 2022-2025, Nicholas Tierney" 
  page-navigation: true
  search: true
  chapters:
    - "index.qmd"
    - "license.qmd"
    - "installation.qmd"
    - "why-qmd.qmd"
    - "rstudio.qmd"
    - "workflow.qmd"
    - "using-qmd.qmd"
    - "pdf-html-word.qmd"
    - "keyboard-shortcuts.qmd"
    - "figures-tables-captions.qmd"
    - "changing-figures.qmd"
    - "math.qmd"
    - "cite-fig-tab-sec.qmd"
    - "citations-and-styles.qmd"
    - "caption-reference-eqn.qmd"
    - "common-problems.qmd"
    - "alternative-outputs-and-exts.qmd"
    - "next-steps.qmd"
    - "references.qmd"
    - "acknowledgements.qmd"
  appendices:
    - "appendix-visual-vs-source-mode.qmd"
    - "appendix-template.qmd"
    - "appendix-faq.qmd"
    - "appendix-html-extensions.qmd"
    - "appendix-manuscript.qmd"
bibliography:
  - book.bib
  - packages.bib

format:
  html:
    theme: 
      - cosmo
      - qmd4sci.scss
    code-background: true
    code-copy: true
    code-overflow: wrap
    toc: true
  pdf:
    documentclass: krantz
    keep-tex: true
    cite-method: natbib
execute: 
  freeze: false
  # epub:
  #   cover-image: cover.png

