# Different Outputs and Extensions 

There are many different outputs for Quarto - as a start, THIS VERY BOOK IS WRITTEN IN QUARTO! How cool is that? I think it's pretty cool.

What's especially great is that the extra barriers to moving from one format to another are relatively low. Generally speaking, the things that you will change in your overall setup are:

- Adding a `_quarto.yml` file
  - Making some changes inside this file to tell it whether it is a book/manuscript/slideshow
  
There are some small differences in how files are setup, but by and large the work that you need to do will be on the writing of the content, and your code. Which is good! That's where we want out focus to be.

## Alternative output formats

- [Write a book](https://quarto.org/docs/books/)
- [build a website](https://quarto.org/docs/websites/)
- [create a simple dashboard](https://quarto.org/docs/dashboards/)
- [use shiny with Quarto](https://quarto.org/docs/interactive/shiny/)
- [generate multiple reports with parameterised reports](https://quarto.org/docs/computations/parameters.html) - [blog post by Mike Mahoney](https://www.mm218.dev/posts/2022-08-04-how-to-use-quarto-for-parameterized-reporting/), [blog post by Mandy Norrbo](https://www.jumpingrivers.com/blog/r-parameterised-presentations-quarto/)
- [typst](https://quarto.org/docs/output-formats/typst.html) (like a next-generation LaTeX - still new.)

### Slideshows / Presentations

- [HTML: revealjs](https://quarto.org/docs/presentations/revealjs/)
- [PDF: beamer](https://quarto.org/docs/presentations/beamer.html)
- [powerpoint](https://quarto.org/docs/presentations/powerpoint.html)

### Quarto Extensions

Quarto has an official extensions API, you can see all their extensions on their [extensions page](https://quarto.org/docs/extensions/). Perhaps the most relevant is the journal extensions page, which I discuss below. For more information on creating extensions, see their [creating extensions page](https://quarto.org/docs/extensions/creating.html).

#### For Journals

Quarto has provided a substantial list of supported journal formats in the [journal listings Quarto extensions page](https://quarto.org/docs/extensions/listing-journals.html). This is similar to [rticles](https://cran.r-project.org/web/packages/rticles/index.html) in rmarkdown.

#### Other extensions

Other formats and extensions for PDF, for example, the [`hikmah.pdf`](https://github.com/andrewheiss/hikmah-academic-quarto) extension by [Andrew Heiss](https://www.andrewheiss.com/).

These can be found at the [Quarto Custom Formats Page](https://quarto.org/docs/extensions/listing-formats.html).
