---
title: "Exploring gapminder"
author: "Nicholas Tierney"
format: 
  html:
    toc: true
    toc-depth: 2
    fig-align: center
    fig-width: 4
    fig-height: 4
    fig-format: png
execute: 
  echo: true
  cache: true
---

```{r}
#| label: library
library(tidyverse)
library(visdat)
library(broom)
```

````{r}
#| label: functions
# A function to scale input to 0-1
scale_01 <- function(x){
  (x - min(x, na.rm = TRUE)) / diff(range(x, na.rm = TRUE))
}
```

# Data reading in here

```{r}
#| label: data-read-in
#| echo: false
#| message: false
#| cache: false
data <- read_csv(here::here("data", "oz_gapminder.csv"))
```

```{r}
#| label: demo
#| eval: true
#| echo: true
1 + 1
```

# Introduction

let's look at the lifespan

```{r}
#| label: hist-life-exp
hist(data$lifeExp)
```

Let's look at the GDP per capita

```{r}
#| label: example-cache
hist(data$gdpPercap)
```

Let's fit a simple linear model of the effect of year on life expectancy

```{r}
#| label: example-lm
fit <- lm(lifeExp ~ year, data = data)
fit
```

And let's look at the coefficient table:

```{r}
#| label: coef-table
fit_coef <- tidy(fit)
knitr::kable(fit_coef,
             caption = "A table of the coefficients")
year_slope <- round(fit_coef$estimate[2], 3)
```

The effect of year on life expectancy is `r year_slope`.

# Bibliography
