---
title: "Introduction document"
author: "Nicholas Tierney"
format: 
  html:
    toc: true
    toc-depth: 2
    fig-align: center
    fig-width: 4
    fig-height: 4
    fig-format: png
execute:
  echo: false
  cache: true
---

````{r}
#| label: library
library(tidyverse)
library(visdat)
```

````{r}
#| label: functions
# A function to scale input to 0-1
scale_01 <- function(x){
  (x - min(x, na.rm = TRUE)) / diff(range(x, na.rm = TRUE))
}
```

```{r}
#| label: data-read-in
data <- read_csv(here::here("data", "oz_gapminder.csv"))
```

# Introduction

This code will be cached

```{r}
#| label: example-cache

```

This code will not run

```{r}
#| label: example-eval
#| eval: false
plot()
```

This code will have the output printed, but the code will not be printed

```{r}
#| label: example-echo
#| echo: false
plot(iris)
```

none of the output of this will be included (equivalent to `echo = FALSE, message = FALSE, error = FALSE, warning = FALSE`)

```{r}
#| label: example-include
#| include: false

```


# Bibliography
